### ISSUE TITLE
shift optimization failing to detect constant shift amounts

### ISSUE THREAD

**Issue by zzzoom** [ispc/ispc#1320]
While trying out ISPC I tried to implement a simple vector prefix sum:
```
int32 gang_scan(int32 v) {
    for (uniform int s = 1; s < programCount; s *= 2) {
        v += shift(v, -s);
    }
    return v;
}
```
Compiling it results in a performance warning: `Stdlib shift() called without constant shift amount.`.

Fair enough, let's try with constants:
```
int32 gang_scan(int32 v) {
    v += shift(v, -1);
    v += shift(v, -2);
    v += shift(v, -4);
    return v;
}
```

ISPC threw the same performance warning again, and it generated pretty much the same asm, shifting on the stack instead of shuffling registers:

```
        .text
        .file   "gangscan_const.ispc"
        .globl  gang_scan___vyi         # -- Begin function gang_scan___vyi
        .p2align        4, 0x90
        .type   gang_scan___vyi,@function
gang_scan___vyi:                        # @gang_scan___vyi
# BB#0:                                 # %allocas
        pushq   %rbp
        movq    %rsp, %rbp
        andq    $-32, %rsp
        subq    $96, %rsp
        vxorps  %ymm1, %ymm1, %ymm1
        vmovaps %ymm1, (%rsp)
        vmovdqa %ymm0, 32(%rsp)
        vpaddd  28(%rsp), %ymm0, %ymm0
        vmovaps %ymm1, (%rsp)
        vmovdqa %ymm0, 32(%rsp)
        vpaddd  24(%rsp), %ymm0, %ymm0
        vmovaps %ymm1, (%rsp)
        vmovdqa %ymm0, 32(%rsp)
        vpaddd  16(%rsp), %ymm0, %ymm0
        movq    %rbp, %rsp
        popq    %rbp
        retq
.Lfunc_end0:
        .size   gang_scan___vyi, .Lfunc_end0-gang_scan___vyi
                                        # -- End function

        .ident  "clang version 5.0.0 (tags/RELEASE_500/final 317690)"
        .section        ".note.GNU-stack","",@progbits
```

I've been able to reproduce this using the current repository head, and also with the 1.9.2, 1.8.0 and 1.7.0 packaged binaries.

I'm not familiar with LLVM so I couldn't figure out why `shiftAmt` in [`opt.cpp`](https://github.com/ispc/ispc/blob/4a28eaad1a164051be0a66151fa72f59f458137a/opt.cpp#L5447) isn't a lvm::Constant. Any ideas?

**Comment by dbabokin** [comment]
Fixed.

**Comment by zzzoom** [comment]
The hardcoded snippet works now, but the original loop using programCount still doesn't. Shouldn't ispc unroll it by default?

**Comment by dbabokin** [comment]
There's no guarantee that variable with constant value is propagated to shift parameter by the time the shift() call is lowered. The implementation allows the propagation to happen in some cases, though. That's may be a little confusing.

So you can read it as follows: requirement is to have real constant (constexpr in C++ terminology, if you prefer). In some cases variable with constant values may also work, but not guaranteed.
